### PR TITLE
Team Page responsiveness 

### PR DESCRIPTION
**Pull request by Yashank18**
#167 Fixed. I have optimized responsiveness for this page.
@vegetabill 
Screenshot (96)

### CODE REVIEW

**Comment by vegetabill** [comment]
Thanks @Yashank18 I will test it out and let you know!

If you'd like to contribute further, take a look at the open issues for the curriculum repo:
https://github.com/Techtonica/curriculum/blob/master/CONTRIBUTING.md

**Comment by vegetabill** [comment]
@gsong as you know I don't know much about Flask but why are the `static/css` files even checked into Git if it's built by sass? I would've expected it to be ignored and then built during dev or deployment.

**Comment by Yashank18** [comment]
@vegetabill for running it offline I used virtual env as mentioned in README. I used those instructions to run it. There were some issues, one of my friends helped me with that.
And sorry I didn't read that we are not supposed to change those files. I am working on it and will get back with a proper solution to this.

**Comment by Yashank18** [comment]
@vegetabill 
I have made the requested changes  in scss file that fixes the issue and it changes the css files by default

**Comment by Yashank18** [comment]
@vegetabill can you please check this PR

**Comment by Yashank18** [comment]
@vegetabill I believe this PR must have been lost in your work flow.
Commenting just in case you have missed the notification of this :)

**Comment by MichelleGlauser** [comment]
@vegetabill is not working at Techtonica anymore. @rogue0137 can you help?

**Comment by rogue0137** [comment]
@Yashank18 going to merge another PR to get the Docker stuff up and then will check confirm your changes still work. Thx for doing this! I'm also in the slack if it's easier to discuss there

**Comment by rogue0137** [comment]
Looks good. Merging!

**Comment by Yashank18** [comment]
Thankyou @rogue0137 😊

**Pull request merged**
