### PR TITLE
Support pyenv

### PR DESCRIPTION
**Pull request by vegetabill**
Add pyenv support so contributors don't have to manually check their python version

### CODE REVIEW

**Comment by gsong** [comment]
I don't think this is necessary, as development should be done via a virtual environment anyway. So the version of Python would be locked at the time when the virtaulenv is created.

Locking this down via pyenv is disruptive to a developer's local workflow, if they depend on Python tools for their own local shell environments. E.g. using `powerline` when my default Python is 3.7, when pyenv switches automatically to 3.6, my shell environment is now broken.

**Comment by vegetabill** [comment]
Okay fair enough. I would suggest adding instructions for what virtualized dev env you suggest for this project then. I'm not a python expert and don't really know what you're talking about.

**Comment by gsong** [comment]
There's a link to learn more about virtualenvs in the README: https://github.com/Techtonica/techtonica.org#running-locally

For me, which virtualenv strategy you decide to take as a developer is up to you, as it depends on your own workflow. But you should definitely submit another PR if you feel the README should be more opinionated about the project setup.

BTW, just to be clear, I'm a volunteer as well. 😁

**Comment by vegetabill** [comment]
@gsong thanks I missed that line in the README. I think that's totally sufficient. I'll check it out. So many env tools in the world these days.

**Pull request closed without merging**
