### PR TITLE
Several accessibility updates - hopefully address issue #144

### PR DESCRIPTION
**Pull request by blueocto**
Basically, mixing HTTP with HTTPS, not good. Source: https://www.chromestatus.com/feature/5633521622188032

### CODE REVIEW

**Comment by blueocto** [comment]
> @blueocto I think it got out of sync because of time. Feel free to merge in from master and update what's needed. Once that's done, re-request me. I can check it then. Also, don't forget to make sure it looks good on your local!

Hey, yeah it's been a while! heh. I've pulled the project back down again, and tried running the pip commands and also tried the docker option and neither like me! I'm not sure how I set it up last time, but I can't run it locally to check for any issues :-(

If it helps, the error reported when running `pip install -r requirements.txt` are:

```
ERROR: matplotlib 1.3.1 requires nose, which is not installed.
ERROR: matplotlib 1.3.1 requires tornado, which is not installed.
Installing collected packages: certifi, chardet, click, urllib3, idna, requests, eventbrite, itsdangerous, werkzeug, flask, flask-sslify, six, pip-tools, python-dateutil, typing, python-dotenv
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/certifi-2019.6.16.dist-info'
Consider using the `--user` option or check the permissions.
```

and when running docker commands;

```
arolines-MBP:sites admin$ cd techtonica.org/
Carolines-MBP:techtonica.org admin$ docker build --tag techtonica .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/admin/sites/techtonica.org/Dockerfile: no such file or directory
Carolines-MBP:techtonica.org admin$ docker run techtonica
Unable to find image 'techtonica:latest' locally
docker: Error response from daemon: pull access denied for techtonica, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by blueocto** [comment]
I dont use pip or Docker, so this is a learning experience for me!

**Comment by rogue0137** [comment]
@blueocto are you on the Tecthonica slack? I'm on there as Krys Flores. Ping me and I can set up time for us to go through it together this weekend :)

**Comment by blueocto** [comment]
> @blueocto are you on the Tecthonica slack? I'm on there as Krys Flores. Ping me and I can set up time for us to go through it together this weekend :)

no I'm not, I'd love an invite so I can help out on the project :-) my email is caroline@blueocto.co.uk

**Comment by MichelleGlauser** [comment]
@blueocto Could you please fill out our volunteer form and then you'll get an invitation to the Slack? http://bit.ly/volunteer-with-Techtonica

**Pull request closed without merging**
