### PR TITLE
skip eventbrite for local development

### PR DESCRIPTION
**Pull request by vegetabill**
* add error msg  looking for .env
* improve outage message to take user to eventbrite, which is likely not still down

### CODE REVIEW

**Comment by gsong** [comment]
Why do we want to skip interacting with Eventbrite for local development?

**Comment by vegetabill** [comment]
Maybe the website is a different type of repo, but IMHO for any open source project folks should be able to checkout the repo and start the app. Right now it blows up. This is not the developer experience we should aim for if we want contributions. For example, I wanted to make a small CSS fix and that was the intro to this codebase. I don't think I should have to care about Eventbrite or get a sensitive key from someone.

Happy to solve this another way or just be up-front in the docs that it's not a fully open repo and contributors should contact you or whoever manages this to get the key or input into their idea.

Up to you.

**Comment by gsong** [comment]
Good point, only trusted developers should have access to the secrets. There are ultimately two issues here:

1. Don't require the `EVENTBRITE_OAUTH_TOKEN` environment variable.
1. Display the proper message in the UI:
    * Can't retrieve events due to configuration or API access error.
    * There are no events.

Can you think of a simpler solution to address both?

**Comment by gsong** [comment]
FYI, #168 will most likely be accepted before this, so perhaps key your proposed solution off of that.

**Comment by vegetabill** [comment]
Hi @gsong thanks for the open-ended request for a "simpler solution" but a lot of time has gone by and you have not solved this dev env issue and so I'm merging this PR. 

If you want to simplify or expand on it, feel free, but I'm not leaving the dev env in a broken state while we wait for this. This is an open-source project and it should run without errors for contributors.

**Comment by gsong** [comment]
@vegetabill This PR completely broke the Eventbrite integration, did you test it on staging prior to pushing to production?

Techtonica__Bridging_the_Tech_Gap

/cc @MichelleGlauser

**Comment by gsong** [comment]
@vegetabill Also, this PR introduced a bunch of flake8 (Python linter) and Black (Python formatting) issues. I would suggest fixing them.

**Comment by vegetabill** [comment]
@gsong sorry about that. I didn't see this notification until now when I came to look if there was a "revert" button because I saw prod was broken. 

I didn't push anything to production but is CI just doing it automatically? The README implied it was all manual so this is a surprise. Linting is not mentioned in the README either so I'll try to figure out what commands should run and add them in. IMHO, they should be commit hooks if they are important.

I'm going to just revert it for now since I don't want to leave it broken.

**Comment by vegetabill** [comment]
@gsong @MichelleGlauser Master now no longer has these changes. I can't really verify them because the app can't load without a valid EB key. But if one of you could verify it and redeploy then prod should be okay again.

**Pull request merged**
